pipeline {
    agent any
    tools {
        jdk   'Java-21'
        maven 'Maven'
    }
    stages {
        stage('Compilar') {
            steps {
                // Obligamos a Jenkins a entrar en la carpeta del proyecto
                dir('examen-tests') { 
                    sh 'mvn clean compile'
                }
            }
        }
        stage('Tests') {
            steps {
                dir('examen-tests') {
                    sh 'mvn test'
                }
            }
        }
        stage('Empaquetar') {
            steps {
                dir('examen-tests') {
                    sh 'mvn package -DskipTests'
                    archiveArtifacts artifacts: 'target/*.jar', fingerprint: true
                }
            }
        }
    }
    post {
        failure { echo '❌ Build fallido' }
        always { cleanWs() }
    }
}
